#ifndef THUMBSTICK_HPP
#define THUMBSTICK_HPP
#pragma once

#define THUMBSTICK_XDELTA_POSITIVE			200
#define THUMBSTICK_XDELTA_NEGATIVE			200
#define THUMBSTICK_YDELTA_POSITIVE			200
#define THUMBSTICK_YDELTA_NEGATIVE			200

#endif